// Generated by scripts/gen-models.py — ERPNext v16 + TaxMate v16 schemas.
// Regenerate after any DocType change. Do not edit by hand.


/**
 * DocType: `Sales Taxes and Charges` — module Accounts
 * Generated from the app source — do not edit by hand.
 */
export interface SalesTaxesAndCharges {
  name: string;
  owner?: string;
  creation?: string;
  modified?: string;
  modified_by?: string;
  docstatus?: 0 | 1 | 2;
  idx?: number;
  /** Type */
  charge_type: "Actual" | "On Net Total" | "On Previous Row Amount" | "On Previous Row Total" | "On Item Quantity";
  /** Reference Row # */
  row_id?: string;
  /** Account Head → Account */
  account_head: string;
  /** Cost Center → Cost Center */
  cost_center?: string;
  /** Description */
  description: string;
  /** Is this Tax included in Basic Rate? */
  included_in_print_rate?: 0 | 1;
  /** Tax Rate */
  rate?: number;
  /** Amount */
  tax_amount?: number;
  /** Total (read-only) */
  total?: number;
  /** Tax Amount After Discount Amount (read-only) */
  tax_amount_after_discount_amount?: number;
  /** Amount (Company Currency) (read-only) */
  base_tax_amount?: number;
  /** Total (Company Currency) (read-only) */
  base_total?: number;
  /** Tax Amount After Discount Amount (Company Currency) (read-only) */
  base_tax_amount_after_discount_amount?: number;
  /** Project → Project */
  project?: string;
  /** Considered In Paid Amount */
  included_in_paid_amount?: 0 | 1;
  /** Don't Recompute Tax (read-only) */
  dont_recompute_tax?: 0 | 1;
  /** Account Currency → Currency (read-only) */
  account_currency?: string;
  /** Net Amount (read-only) */
  net_amount?: number;
  /** Net Amount (Company Currency) (read-only) */
  base_net_amount?: number;
  /** Set by Item Tax Template (read-only) */
  set_by_item_tax_template?: 0 | 1;
  /** Is Tax Withholding Account (read-only) */
  is_tax_withholding_account?: 0 | 1;
}

/**
 * DocType: `Payment Schedule` — module Accounts
 * Generated from the app source — do not edit by hand.
 */
export interface PaymentSchedule {
  name: string;
  owner?: string;
  creation?: string;
  modified?: string;
  modified_by?: string;
  docstatus?: 0 | 1 | 2;
  idx?: number;
  /** Payment Term → Payment Term */
  payment_term?: string;
  /** Description */
  description?: string;
  /** Due Date */
  due_date: string;
  /** Invoice Portion */
  invoice_portion?: number;
  /** Payment Amount */
  payment_amount: number;
  /** Mode of Payment → Mode of Payment */
  mode_of_payment?: string;
  /** Paid Amount */
  paid_amount?: number;
  /** Discounted Amount (read-only) */
  discounted_amount?: number;
  /** Outstanding (read-only) */
  outstanding?: number;
  /** Discount Date */
  discount_date?: string;
  /** Discount Type */
  discount_type?: "Percentage" | "Amount";
  /** Discount */
  discount?: number;
  /** Payment Amount (Company Currency) */
  base_payment_amount?: number;
  /** Outstanding (Company Currency) (read-only) */
  base_outstanding?: number;
  /** Paid Amount (Company Currency) (read-only) */
  base_paid_amount?: number;
  /** Due Date Based On (read-only) */
  due_date_based_on?: "Day(s) after invoice date" | "Day(s) after the end of the invoice month" | "Month(s) after the end of the invoice month";
  /** Credit Days (read-only) */
  credit_days?: number;
  /** Credit Months (read-only) */
  credit_months?: number;
  /** Discount Validity Based On (read-only) */
  discount_validity_based_on?: "Day(s) after invoice date" | "Day(s) after the end of the invoice month" | "Month(s) after the end of the invoice month";
  /** Discount Validity (read-only) */
  discount_validity?: number;
}

/**
 * DocType: `Sales Order` — module Selling
 * Generated from the app source — do not edit by hand.
 */
export interface SalesOrder {
  name: string;
  owner?: string;
  creation?: string;
  modified?: string;
  modified_by?: string;
  docstatus?: 0 | 1 | 2;
  idx?: number;
  /** Series */
  naming_series: "SAL-ORD-.YYYY.-";
  /** Customer → Customer */
  customer: string;
  /** Customer Name (read-only) */
  customer_name?: string;
  /** Order Type */
  order_type?: "Sales" | "Maintenance" | "Shopping Cart";
  /** Amended From → Sales Order (read-only) */
  amended_from?: string;
  /** Company → Company */
  company: string;
  /** Date */
  transaction_date?: string;
  /** Delivery Date */
  delivery_date?: string;
  /** Customer's Purchase Order */
  po_no?: string;
  /** Customer's Purchase Order Date */
  po_date?: string;
  /** Tax Id (read-only) */
  tax_id?: string;
  /** Customer Address → Address */
  customer_address?: string;
  /** Address (read-only) */
  address_display?: string;
  /** Contact Person → Contact */
  contact_person?: string;
  /** Contact (read-only) */
  contact_display?: string;
  /** Mobile No (read-only) */
  contact_mobile?: string;
  /** Contact Email (read-only) */
  contact_email?: string;
  /** Company Address (read-only) */
  company_address_display?: string;
  /** Company Address Name → Address */
  company_address?: string;
  /** Shipping Address Name → Address */
  shipping_address_name?: string;
  /** Shipping Address (read-only) */
  shipping_address?: string;
  /** Customer Group → Customer Group */
  customer_group?: string;
  /** Territory → Territory */
  territory?: string;
  /** Currency → Currency */
  currency: string;
  /** Exchange Rate */
  conversion_rate: number;
  /** Price List → Price List */
  selling_price_list: string;
  /** Price List Currency → Currency (read-only) */
  price_list_currency: string;
  /** Price List Exchange Rate */
  plc_conversion_rate: number;
  /** Ignore Pricing Rule */
  ignore_pricing_rule?: 0 | 1;
  /** Set Source Warehouse → Warehouse */
  set_warehouse?: string;
  /** Scan Barcode */
  scan_barcode?: string;
  /** Items */
  items: SalesOrderItem[];
  /** Pricing Rule Detail (read-only) */
  pricing_rules?: Record<string, unknown>[];
  /** Total Quantity (read-only) */
  total_qty?: number;
  /** Total (Company Currency) (read-only) */
  base_total?: number;
  /** Net Total (Company Currency) (read-only) */
  base_net_total?: number;
  /** Total (read-only) */
  total?: number;
  /** Net Total (read-only) */
  net_total?: number;
  /** Total Net Weight (read-only) */
  total_net_weight?: number;
  /** Tax Category → Tax Category */
  tax_category?: string;
  /** Shipping Rule → Shipping Rule */
  shipping_rule?: string;
  /** Sales Taxes and Charges Template → Sales Taxes and Charges Template */
  taxes_and_charges?: string;
  /** Sales Taxes and Charges */
  taxes?: SalesTaxesAndCharges[];
  /** Taxes and Charges Calculation (read-only) */
  other_charges_calculation?: string;
  /** Total Taxes and Charges (Company Currency) (read-only) */
  base_total_taxes_and_charges?: number;
  /** Total Taxes and Charges (read-only) */
  total_taxes_and_charges?: number;
  /** Loyalty Points (read-only) */
  loyalty_points?: number;
  /** Loyalty Amount (read-only) */
  loyalty_amount?: number;
  /** Coupon Code → Coupon Code */
  coupon_code?: string;
  /** Apply Additional Discount On */
  apply_discount_on?: "Grand Total" | "Net Total";
  /** Additional Discount Amount (read-only) */
  base_discount_amount?: number;
  /** Additional Discount Percentage */
  additional_discount_percentage?: number;
  /** Additional Discount Amount */
  discount_amount?: number;
  /** Grand Total (read-only) */
  base_grand_total?: number;
  /** Rounding Adjustment (read-only) */
  base_rounding_adjustment?: number;
  /** Rounded Total (read-only) */
  base_rounded_total?: number;
  /** In Words (read-only) */
  base_in_words?: string;
  /** Grand Total (read-only) */
  grand_total?: number;
  /** Rounding Adjustment (read-only) */
  rounding_adjustment?: number;
  /** Rounded Total (read-only) */
  rounded_total?: number;
  /** In Words (read-only) */
  in_words?: string;
  /** Advance Paid (read-only) */
  advance_paid?: number;
  /** Packed Items */
  packed_items?: Record<string, unknown>[];
  /** Payment Terms Template → Payment Terms Template */
  payment_terms_template?: string;
  /** Payment Schedule */
  payment_schedule?: PaymentSchedule[];
  /** Terms → Terms and Conditions */
  tc_name?: string;
  /** Terms and Conditions Details */
  terms?: string;
  /** Inter Company Order Reference → Purchase Order (read-only) */
  inter_company_order_reference?: string;
  /** Project → Project */
  project?: string;
  /** Party Account Currency → Currency (read-only) */
  party_account_currency?: string;
  /** Print Language → Language (read-only) */
  language?: string;
  /** Letter Head → Letter Head */
  letter_head?: string;
  /** Print Heading → Print Heading */
  select_print_heading?: string;
  /** Group same items */
  group_same_items?: 0 | 1;
  /** Status (read-only) */
  status?: "Draft" | "On Hold" | "To Pay" | "To Deliver and Bill" | "To Bill" | "To Deliver" | "Completed" | "Cancelled" | "Closed";
  /** Delivery Status */
  delivery_status?: "Not Delivered" | "Fully Delivered" | "Partly Delivered" | "Closed" | "Not Applicable";
  /** %  Delivered (read-only) */
  per_delivered?: number;
  /** % Amount Billed (read-only) */
  per_billed?: number;
  /** Billing Status */
  billing_status?: "Not Billed" | "Fully Billed" | "Partly Billed" | "Closed";
  /** Sales Partner → Sales Partner */
  sales_partner?: string;
  /** Commission Rate */
  commission_rate?: number;
  /** Total Commission */
  total_commission?: number;
  /** Sales Team */
  sales_team?: Record<string, unknown>[];
  /** From Date */
  from_date?: string;
  /** To Date */
  to_date?: string;
  /** Auto Repeat → Auto Repeat */
  auto_repeat?: string;
  /** Phone (read-only) */
  contact_phone?: string;
  /** Skip Delivery Note */
  skip_delivery_note?: 0 | 1;
  /** Is Internal Customer (read-only) */
  is_internal_customer?: 0 | 1;
  /** Represents Company → Company (read-only) */
  represents_company?: string;
  /** Disable Rounded Total */
  disable_rounded_total?: 0 | 1;
  /** Dispatch Address Name → Address */
  dispatch_address_name?: string;
  /** Dispatch Address (read-only) */
  dispatch_address?: string;
  /** Amount Eligible for Commission (read-only) */
  amount_eligible_for_commission?: number;
  /** % Picked (read-only) */
  per_picked?: number;
  /** Cost Center → Cost Center */
  cost_center?: string;
  /** Incoterm → Incoterm */
  incoterm?: string;
  /** Named Place */
  named_place?: string;
  /** Reserve Stock */
  reserve_stock?: 0 | 1;
  /** Advance Payment Status */
  advance_payment_status?: "Not Requested" | "Requested" | "Partially Paid" | "Fully Paid";
  /** Medium → UTM Medium */
  utm_medium?: string;
  /** Content */
  utm_content?: string;
  /** Source → UTM Source */
  utm_source?: string;
  /** Campaign → UTM Campaign */
  utm_campaign?: string;
  /** Company Contact Person → Contact */
  company_contact_person?: string;
  /** Has Unit Price Items */
  has_unit_price_items?: 0 | 1;
  /** Last Scanned Warehouse */
  last_scanned_warehouse?: string;
  /** Is Subcontracted */
  is_subcontracted?: 0 | 1;
  /** Item Wise Tax Details */
  item_wise_tax_details?: Record<string, unknown>[];
  /** Time */
  transaction_time?: string;
  /** Ignore Default Payment Terms Template (read-only) */
  ignore_default_payment_terms_template?: 0 | 1;
  /** Title */
  title?: string;
}

/**
 * DocType: `Sales Order Item` — module Selling
 * Generated from the app source — do not edit by hand.
 */
export interface SalesOrderItem {
  name: string;
  owner?: string;
  creation?: string;
  modified?: string;
  modified_by?: string;
  docstatus?: 0 | 1 | 2;
  idx?: number;
  /** Item Code → Item */
  item_code: string;
  /** Customer's Item Code (read-only) */
  customer_item_code?: string;
  /** Ensure Delivery Based on Produced Serial No */
  ensure_delivery_based_on_produced_serial_no?: 0 | 1;
  /** Item Name */
  item_name: string;
  /** Description */
  description?: string;
  /** Delivery Date */
  delivery_date?: string;
  /** Image */
  image?: string;
  /** Image View */
  image_view?: unknown;
  /** Quantity */
  qty: number;
  /** Stock UOM → UOM (read-only) */
  stock_uom?: string;
  /** UOM → UOM */
  uom: string;
  /** UOM Conversion Factor (read-only) */
  conversion_factor: number;
  /** Qty as per Stock UOM (read-only) */
  stock_qty?: number;
  /** Price List Rate (read-only) */
  price_list_rate?: number;
  /** Price List Rate (Company Currency) (read-only) */
  base_price_list_rate?: number;
  /** Margin Type */
  margin_type?: "Percentage" | "Amount";
  /** Margin Rate or Amount */
  margin_rate_or_amount?: number;
  /** Rate With Margin (read-only) */
  rate_with_margin?: number;
  /** Discount (%) on Price List Rate with Margin */
  discount_percentage?: number;
  /** Discount Amount */
  discount_amount?: number;
  /** Rate With Margin (Company Currency) (read-only) */
  base_rate_with_margin?: number;
  /** Rate */
  rate?: number;
  /** Amount (read-only) */
  amount?: number;
  /** Basic Rate (Company Currency) (read-only) */
  base_rate?: number;
  /** Amount (Company Currency) (read-only) */
  base_amount?: number;
  /** Pricing Rules (read-only) */
  pricing_rules?: string;
  /** Is Free Item (read-only) */
  is_free_item?: 0 | 1;
  /** Net Rate (read-only) */
  net_rate?: number;
  /** Net Amount (read-only) */
  net_amount?: number;
  /** Net Rate (Company Currency) (read-only) */
  base_net_rate?: number;
  /** Net Amount (Company Currency) (read-only) */
  base_net_amount?: number;
  /** Supplier delivers to Customer */
  delivered_by_supplier?: 0 | 1;
  /** Supplier → Supplier */
  supplier?: string;
  /** Weight Per Unit */
  weight_per_unit?: number;
  /** Total Weight (read-only) */
  total_weight?: number;
  /** Weight UOM → UOM */
  weight_uom?: string;
  /** Source Warehouse → Warehouse */
  warehouse?: string;
  /** Customer Warehouse (Optional) → Warehouse */
  target_warehouse?: string;
  /** Quotation → Quotation (read-only) */
  prevdoc_docname?: string;
  /** Brand Name → Brand (read-only) */
  brand?: string;
  /** Item Group → Item Group (read-only) */
  item_group?: string;
  /** Billed Amt (read-only) */
  billed_amt?: number;
  /** Valuation Rate (read-only) */
  valuation_rate?: number;
  /** Gross Profit (read-only) */
  gross_profit?: number;
  /** Blanket Order → Blanket Order */
  blanket_order?: string;
  /** Blanket Order Rate (read-only) */
  blanket_order_rate?: number;
  /** Projected Qty (read-only) */
  projected_qty?: number;
  /** Qty (Warehouse) (read-only) */
  actual_qty?: number;
  /** Ordered Qty (read-only) */
  ordered_qty?: number;
  /** Delivered Qty (read-only) */
  delivered_qty?: number;
  /** Work Order Qty (read-only) */
  work_order_qty?: number;
  /** Returned Qty (read-only) */
  returned_qty?: number;
  /** Item Tax Template → Item Tax Template */
  item_tax_template?: string;
  /** Page Break */
  page_break?: 0 | 1;
  /** Planned Quantity (read-only) */
  planned_qty?: number;
  /** Produced Quantity (read-only) */
  produced_qty?: number;
  /** Item Tax Rate (read-only) */
  item_tax_rate?: string;
  /** Sales Order Date (read-only) */
  transaction_date?: string;
  /** Additional Notes */
  additional_notes?: string;
  /** Against Blanket Order */
  against_blanket_order?: 0 | 1;
  /** BOM No → BOM */
  bom_no?: string;
  /** Rate of Stock UOM (read-only) */
  stock_uom_rate?: number;
  /** Grant Commission (read-only) */
  grant_commission?: 0 | 1;
  /** Picked Qty (in Stock UOM) (read-only) */
  picked_qty?: number;
  /** Purchase Order → Purchase Order (read-only) */
  purchase_order?: string;
  /** Purchase Order Item (read-only) */
  purchase_order_item?: string;
  /** quotation_item (read-only) */
  quotation_item?: string;
  /** Material Request → Material Request */
  material_request?: string;
  /** Material Request Item */
  material_request_item?: string;
  /** Reserve Stock */
  reserve_stock?: 0 | 1;
  /** Stock Reserved Qty (in Stock UOM) (read-only) */
  stock_reserved_qty?: number;
  /** Production Plan Qty (read-only) */
  production_plan_qty?: number;
  /** Is Stock Item */
  is_stock_item?: 0 | 1;
  /** Distributed Discount Amount */
  distributed_discount_amount?: number;
  /** Qty (Company) (read-only) */
  company_total_stock?: number;
  /** Cost Center → Cost Center */
  cost_center?: string;
  /** Project → Project */
  project?: string;
  /** Subcontracted Quantity (read-only) */
  subcontracted_qty?: number;
  /** Finished Good → Item */
  fg_item?: string;
  /** Finished Good Qty */
  fg_item_qty?: number;
  /** Requested Qty (read-only) */
  requested_qty?: number;
}

/**
 * DocType: `Customer` — module Selling
 * Generated from the app source — do not edit by hand.
 */
export interface Customer {
  name: string;
  owner?: string;
  creation?: string;
  modified?: string;
  modified_by?: string;
  docstatus?: 0 | 1 | 2;
  idx?: number;
  /** Series */
  naming_series?: "CUST-.YYYY.-";
  /** Customer Name */
  customer_name: string;
  /** Alias */
  alias?: string;
  /** Gender → Gender */
  gender?: string;
  /** Customer Type */
  customer_type?: "Company" | "Individual" | "Partnership";
  /** Company Bank Account → Bank Account */
  default_bank_account?: string;
  /** Lead → Lead (read-only) */
  lead_name?: string;
  /** Image */
  image?: string;
  /** Account Manager → User */
  account_manager?: string;
  /** Customer Group → Customer Group */
  customer_group?: string;
  /** Territory → Territory */
  territory?: string;
  /** Tax ID */
  tax_id?: string;
  /** Tax Category → Tax Category */
  tax_category?: string;
  /** Disabled */
  disabled?: 0 | 1;
  /** Is Internal Customer */
  is_internal_customer?: 0 | 1;
  /** Represents Company → Company */
  represents_company?: string;
  /** Allowed to transact with */
  companies?: Record<string, unknown>[];
  /** Billing Currency → Currency */
  default_currency?: string;
  /** Price List → Price List */
  default_price_list?: string;
  /** Print Language → Language */
  language?: string;
  /** Website */
  website?: string;
  /** Customer Primary Contact → Contact */
  customer_primary_contact?: string;
  /** Mobile No */
  mobile_no?: string;
  /** Email Id */
  email_id?: string;
  /** Customer Primary Address → Address */
  customer_primary_address?: string;
  /** Primary Address (read-only) */
  primary_address?: string;
  /** Default Accounts */
  accounts?: Record<string, unknown>[];
  /** Payment Terms Template → Payment Terms Template */
  payment_terms?: string;
  /** Customer Details */
  customer_details?: string;
  /** Market Segment → Market Segment */
  market_segment?: string;
  /** Industry → Industry Type */
  industry?: string;
  /** Is Frozen */
  is_frozen?: 0 | 1;
  /** Loyalty Program → Loyalty Program */
  loyalty_program?: string;
  /** Loyalty Program Tier (read-only) */
  loyalty_program_tier?: string;
  /** Sales Partner → Sales Partner */
  default_sales_partner?: string;
  /** Commission Rate */
  default_commission_rate?: number;
  /** Sales Team */
  sales_team?: Record<string, unknown>[];
  /** Customer POS ID (read-only) */
  customer_pos_id?: string;
  /** Credit & Overdue Limits */
  credit_limits?: Record<string, unknown>[];
  /** Allow sales invoice creation without sales order */
  so_required?: 0 | 1;
  /** Allow sales invoice creation without delivery note */
  dn_required?: 0 | 1;
  /** Tax Withholding Category → Tax Withholding Category */
  tax_withholding_category?: string;
  /** Opportunity → Opportunity (read-only) */
  opportunity_name?: string;
  /** Customer Portal Users */
  portal_users?: Record<string, unknown>[];
  /** Prospect → Prospect (read-only) */
  prospect_name?: string;
  /** First Name */
  first_name?: string;
  /** Last Name */
  last_name?: string;
  /** Supplier Numbers */
  supplier_numbers?: Record<string, unknown>[];
  /** Tax Withholding Group → Tax Withholding Group */
  tax_withholding_group?: string;
}

/**
 * DocType: `Item` — module Stock
 * Generated from the app source — do not edit by hand.
 */
export interface Item {
  name: string;
  owner?: string;
  creation?: string;
  modified?: string;
  modified_by?: string;
  docstatus?: 0 | 1 | 2;
  idx?: number;
  /** Series */
  naming_series?: "STO-ITEM-.YYYY.-";
  /** Item Code */
  item_code: string;
  /** Variant Of → Item (read-only) */
  variant_of?: string;
  /** Item Name */
  item_name?: string;
  /** Item Group → Item Group */
  item_group: string;
  /** Default Unit of Measure → UOM */
  stock_uom: string;
  /** Disabled */
  disabled?: 0 | 1;
  /** Allow Alternative Item */
  allow_alternative_item?: 0 | 1;
  /** Maintain Stock */
  is_stock_item?: 0 | 1;
  /** Include Item In Manufacturing */
  include_item_in_manufacturing?: 0 | 1;
  /** Opening Stock */
  opening_stock?: number;
  /** Valuation Rate */
  valuation_rate?: number;
  /** Standard Selling Rate */
  standard_rate?: number;
  /** Is Fixed Asset */
  is_fixed_asset?: 0 | 1;
  /** Asset Category → Asset Category */
  asset_category?: string;
  /** Asset Naming Series */
  asset_naming_series?: string;
  /** Image */
  image?: string;
  /** Brand → Brand */
  brand?: string;
  /** Description */
  description?: string;
  /** Barcodes */
  barcodes?: Record<string, unknown>[];
  /** Shelf Life In Days */
  shelf_life_in_days?: number;
  /** End of Life */
  end_of_life?: string;
  /** Default Material Request Type */
  default_material_request_type?: "Purchase" | "Material Transfer" | "Material Issue" | "Manufacture" | "Customer Provided";
  /** Valuation Method */
  valuation_method?: "FIFO" | "Moving Average" | "LIFO";
  /** Warranty Period (in days) */
  warranty_period?: string;
  /** Weight Per Unit */
  weight_per_unit?: number;
  /** Weight UOM → UOM */
  weight_uom?: string;
  /** Reorder level based on Warehouse */
  reorder_levels?: Record<string, unknown>[];
  uoms?: Record<string, unknown>[];
  /** Has Batch No */
  has_batch_no?: 0 | 1;
  /** Automatically Create New Batch */
  create_new_batch?: 0 | 1;
  /** Batch Number Series */
  batch_number_series?: string;
  /** Has Expiry Date */
  has_expiry_date?: 0 | 1;
  /** Retain Sample */
  retain_sample?: 0 | 1;
  /** Max Sample Quantity */
  sample_quantity?: number;
  /** Has Serial No */
  has_serial_no?: 0 | 1;
  /** Serial Number Series */
  serial_no_series?: string;
  /** Has Variants */
  has_variants?: 0 | 1;
  /** Variant Based On */
  variant_based_on?: "Item Attribute" | "Manufacturer";
  /** Variant Attributes */
  attributes?: Record<string, unknown>[];
  /** Item Defaults */
  item_defaults?: Record<string, unknown>[];
  /** Allow Purchase */
  is_purchase_item?: 0 | 1;
  /** Default Purchase Unit of Measure → UOM */
  purchase_uom?: string;
  /** Minimum Order Qty */
  min_order_qty?: number;
  /** Safety Stock */
  safety_stock?: number;
  /** Lead Time in days */
  lead_time_days?: number;
  /** Last Purchase Rate (read-only) */
  last_purchase_rate?: number;
  /** Is Customer Provided Item */
  is_customer_provided_item?: 0 | 1;
  /** Delivered by Supplier (Drop Ship) */
  delivered_by_supplier?: 0 | 1;
  /** Item Supplier */
  supplier_items?: Record<string, unknown>[];
  /** Country of Origin → Country */
  country_of_origin?: string;
  /** Customs Tariff Number → Customs Tariff Number */
  customs_tariff_number?: string;
  /** Default Sales Unit of Measure → UOM */
  sales_uom?: string;
  /** Allow Sales */
  is_sales_item?: 0 | 1;
  /** Max Discount (%) */
  max_discount?: number;
  /** Enable Deferred Revenue */
  enable_deferred_revenue?: 0 | 1;
  /** No of Months (Revenue) */
  no_of_months?: number;
  /** Enable Deferred Expense */
  enable_deferred_expense?: 0 | 1;
  /** No of Months (Expense) */
  no_of_months_exp?: number;
  /** Customer Items */
  customer_items?: Record<string, unknown>[];
  /** Taxes */
  taxes?: Record<string, unknown>[];
  /** Inspection Required before Purchase */
  inspection_required_before_purchase?: 0 | 1;
  /** Inspection Required before Delivery */
  inspection_required_before_delivery?: 0 | 1;
  /** Quality Inspection Template → Quality Inspection Template */
  quality_inspection_template?: string;
  /** Default BOM → BOM (read-only) */
  default_bom?: string;
  /** Is Subcontracted Item */
  is_sub_contracted_item?: 0 | 1;
  /** Customer Code */
  customer_code?: string;
  /** Total Projected Qty (read-only) */
  total_projected_qty?: number;
  /** Over Delivery/Receipt Allowance (%) */
  over_delivery_receipt_allowance?: number;
  /** Over Billing Allowance (%) */
  over_billing_allowance?: number;
  /** Auto create assets on purchase */
  auto_create_assets?: 0 | 1;
  /** Default Item Manufacturer → Manufacturer (read-only) */
  default_item_manufacturer?: string;
  /** Default Manufacturer Part No (read-only) */
  default_manufacturer_part_no?: string;
  /** Grant Commission */
  grant_commission?: 0 | 1;
  /** Create Grouped Asset */
  is_grouped_asset?: 0 | 1;
  /** Allow Negative Stock */
  allow_negative_stock?: 0 | 1;
  /** Production Capacity */
  production_capacity?: number;
  /** Purchase Tax Withholding Category → Tax Withholding Category */
  purchase_tax_withholding_category?: string;
  /** Sales Tax Withholding Category → Tax Withholding Category */
  sales_tax_withholding_category?: string;
}
