#!/usr/bin/env python3
"""Generate TypeScript models from real ERPNext + TaxMate DocType JSON schemas."""
import json, re, os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
ERP = os.environ.get("TAXMATE_ERPNEXT_SRC", os.path.join(ROOT, "..", "erpnext"))
TM = os.environ.get("TAXMATE_APP_SRC", os.path.join(ROOT, "taxmate"))
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "types")

TS = {
    "Data":"string","Small Text":"string","Text":"string","Long Text":"string","Text Editor":"string",
    "Code":"string","HTML Editor":"string","Markdown Editor":"string","Password":"string","Read Only":"string",
    "Barcode":"string","Geolocation":"string","JSON":"string","Phone":"string","Color":"string",
    "Int":"number","Float":"number","Currency":"number","Percent":"number","Duration":"number","Rating":"number",
    "Check":"0 | 1","Date":"string","Datetime":"string","Time":"string",
    "Attach":"string","Attach Image":"string","Signature":"string",
    "Select":"string","Link":"string","Dynamic Link":"string","Autocomplete":"string",
}
LAYOUT = {"Section Break","Column Break","Tab Break","HTML","Button","Fold","Heading"}

def iface(dt): return re.sub(r"[^A-Za-z0-9]", "", dt.title().replace(" ", ""))

def ts_type(f, child_map):
    ft = f.get("fieldtype")
    if ft in ("Table","Table MultiSelect"):
        opt = f.get("options")
        return (iface(opt) + "[]") if opt and opt in child_map else "Record<string, unknown>[]"
    if ft == "Select":
        opts = [o.strip() for o in (f.get("options") or "").split("\n") if o.strip()]
        if opts and len(opts) <= 20 and all(len(o) <= 60 for o in opts):
            return " | ".join('"%s"' % o for o in opts)
        return "string"
    return TS.get(ft, "unknown")

def render(dt, fields, child_map, *, custom=False, meta=None):
    meta = meta or {}
    L = ["/**"]
    if custom:
        L.append(" * Custom fields TaxMate adds to ERPNext's `%s`." % dt)
    else:
        L.append(" * DocType: `%s`%s" % (dt, (" — module %s" % meta["module"]) if meta.get("module") else ""))
        if meta.get("issingle"): L.append(" * Single DocType.")
    L.append(" * Generated from the app source — do not edit by hand.")
    L.append(" */")
    L.append("export interface %s%s {" % (iface(dt), "CustomFields" if custom else ""))
    if not custom:
        for base in ("name: string;","owner?: string;","creation?: string;","modified?: string;",
                     "modified_by?: string;","docstatus?: 0 | 1 | 2;","idx?: number;"):
            L.append("  " + base)
    seen = set()
    for f in fields:
        ft, fn = f.get("fieldtype"), f.get("fieldname")
        if ft in LAYOUT or not fn or fn in seen: continue
        seen.add(fn)
        doc = []
        if f.get("label"): doc.append(f["label"])
        if ft in ("Link","Dynamic Link") and f.get("options"): doc.append("→ %s" % f["options"])
        if f.get("read_only"): doc.append("(read-only)")
        if doc: L.append("  /** %s */" % " ".join(doc))
        optional = "" if (f.get("reqd") and not f.get("default")) else "?"
        L.append("  %s%s: %s;" % (fn, optional, ts_type(f, child_map)))
    L.append("}")
    return "\n".join(L)

def load(path):
    d = json.load(open(path))
    return d if "fields" in d else None

TARGETS = [
    (f"{ERP}/erpnext/selling/doctype/sales_order/sales_order.json", "Sales Order"),
    (f"{ERP}/erpnext/selling/doctype/sales_order_item/sales_order_item.json", "Sales Order Item"),
    (f"{ERP}/erpnext/selling/doctype/customer/customer.json", "Customer"),
    (f"{ERP}/erpnext/stock/doctype/item/item.json", "Item"),
]
CHILD = {"Sales Order Item","Sales Taxes and Charges","Payment Schedule"}
EXTRA_CHILD = [
    (f"{ERP}/erpnext/accounts/doctype/sales_taxes_and_charges/sales_taxes_and_charges.json", "Sales Taxes and Charges"),
    (f"{ERP}/erpnext/accounts/doctype/payment_schedule/payment_schedule.json", "Payment Schedule"),
]

parts = ["// Generated by scripts/gen-models.py — ERPNext v16 + TaxMate v16 schemas.\n// Regenerate after any DocType change. Do not edit by hand.\n"]
child_map = {n for _, n in TARGETS} | {n for _, n in EXTRA_CHILD} | CHILD

for path, name in EXTRA_CHILD + TARGETS:
    if not os.path.exists(path):
        parts.append("// NOT FOUND: %s" % name); continue
    d = load(path)
    if not d: continue
    parts.append(render(name, d["fields"], child_map, meta=d))

open(f"{OUT}/erpnext.ts","w").write("\n\n".join(parts) + "\n")

# TaxMate custom fields
src = open(f"{TM}/taxmate/uae_vat/constants/custom_fields.py").read()
ns = {
 "BILLING_FREQUENCY_SELECT_OPTIONS": "\nDLY\nWKY\nQ15\nMTH\nQ45\nQ60\nQTR\nHYR\nYRL\nOTH",
 "PAYMENT_MEANS_SELECT_OPTIONS": "\n" + "\n".join([
   "1 - Instrument not defined","10 - Cash","20 - Cheque","30 - Credit transfer","31 - Debit transfer",
   "42 - Payment to bank account","48 - Bank card","49 - Direct debit","54 - Credit card","55 - Debit card",
   "58 - SEPA credit transfer"]),
}
body = src.split("PARTY_LEGAL_FIELDS", 1)[1]
exec("PARTY_LEGAL_FIELDS" + body, ns)
cf = ns["CUSTOM_FIELDS"]
cparts = ["// TaxMate custom fields on ERPNext DocTypes — generated. Do not edit by hand.\n"]
for dt, fields in cf.items():
    cparts.append(render(dt, fields, child_map, custom=True))
open(f"{OUT}/taxmate.ts","w").write("\n\n".join(cparts) + "\n")

# UAE code lists
cs = open(f"{TM}/taxmate/uae_e_invoicing/constants/__init__.py").read()
cns = {}
exec(cs.replace("from __future__ import annotations",""), cns)
e = ["// UAE / PINT-AE code lists — generated from taxmate constants. Do not edit by hand.\n"]
e.append("export const E_INVOICE_STATUSES = %s as const;" % json.dumps(list(cns["E_INVOICE_STATUSES"])))
e.append("export type EInvoiceStatus = (typeof E_INVOICE_STATUSES)[number];\n")
for k in ("SALES_DOCUMENT_TYPE_CODES","PURCHASE_DOCUMENT_TYPE_CODES","VAT_CATEGORY_CODES",
          "APPROVED_PAYMENT_MEANS","EMIRATE_SUBDIVISION_CODES","BILLING_FREQUENCY_CODES"):
    e.append("export const %s = %s as const;" % (k, json.dumps(cns[k], indent=2, ensure_ascii=False)))
e.append("export const UAE_EMIRATES = %s as const;" % json.dumps(list(cns["EMIRATE_SUBDIVISION_CODES"].keys())))
e.append("export type Emirate = (typeof UAE_EMIRATES)[number];")
e.append('export const PINT_AE_CUSTOMIZATION_ID = "%s";' % cns["PINT_AE_CUSTOMIZATION_ID"])
open(f"{OUT}/uae.ts","w").write("\n\n".join(e) + "\n")
print("generated:", os.listdir(OUT))
